# Site
site_name: Note
site_url: https://yuyahnd.github.io/note/
repo_url: https://github.com/yuyahnd/note

# Theme
theme:
  name: material
  language: ja
  palette:
    primary: black
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - toc.follow

# Plugin
plugins:
  search:
    lang: ja

# Extra
extra:
  generator: false

# Copyright
copyright: 'Copyright © 2023 Yuya Honda.'

# Navigation
nav:
  - Home: index.md
  - Notes:
    - notes/index.md
    - Markdown: notes/markdown.md
    - MkDocs:
      - notes/mkdocs/index.md
    - mermaid:
      - notes/mermaid/index.md
      - Flowchart: notes/mermaid/flowchart.md
  - Code:
    - code/index.md
    - Python:
      - code/python/index.md
